# Generated by Django 3.0.8 on 2020-07-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelpractice', '0002_userinfo_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='test',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
