# Generated by Django 3.0.8 on 2020-07-19 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelrelation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='user',
            new_name='user_relation',
        ),
    ]
